
-- physics:

STATIC_TERRAIN		= 1
DYNAMIC_PROPS		= STATIC_TERRAIN * 2
DYNAMIC_CHARACTER	= DYNAMIC_PROPS * 2
SENSOR				= DYNAMIC_CHARACTER * 2
FLY_WALLS			= SENSOR * 2


-- visibility:
NON_PLAYER	= 1
PLAYER		= NON_PLAYER * 2
